name: Sync forks

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight (UTC)
  workflow_dispatch: # Allow running manually on demand
    inputs:
      provider:
        type: choice
        description: CAPI provider to sync
        options:
        - core
        - operator
        - aws

jobs:
  sync-repo-on-schedule: # Run only on schedule, syncs all CAPI providers
    if: ${{ github.event_name == 'schedule' }}
    strategy:
      matrix:
        providers: ["core", "operator", "aws"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Sync ${{ matrix.providers }} with upstream
      run: ./sync-repo.sh ${{ matrix.providers }} ${{ secrets.PAT }}
  sync-repo-on-demand: # Run only on demand, syncs individual CAPI providers based on input
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Sync ${{ github.event.inputs.provider }} with upstream
      run: ./sync-repo.sh ${{ github.event.inputs.provider }} ${{ secrets.PAT }}
